# Generated by Django 4.1.7 on 2023-02-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AoK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=100)),
                ('recepient', models.CharField(max_length=100)),
                ('act', models.CharField(max_length=200)),
            ],
        ),
    ]
