# Generated by Django 4.1.7 on 2023-02-23 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actsofkindness', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aok',
            old_name='recepient',
            new_name='recipient',
        ),
    ]
